name: Cypress Tests
on:
  workflow_dispatch:

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
    env:
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON }}
  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
    env:
      TARGET_TOKEN_CHROME: ${{ secrets.TARGET_TOKEN_CHROME }}
  cypress-firefox-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
    env:
      TARGET_TOKEN_FIREFOX: ${{ secrets.TARGET_TOKEN_FIREFOX }}
